import type { PolicyPromise, State, RTIFiling } from '@/types'

export const mockState: State = {
  id: 'ka-001',
  name: 'Karnataka',
  code: 'KA',
  capital: 'Bengaluru',
  current_cm: 'Siddaramaiah',
  created_at: '2024-01-01T00:00:00Z',
}

export const mockPromises: PolicyPromise[] = [
  {
    id: '1',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'infrastructure',
    text: 'Establish a Centre for Applied AI with a dedicated budget of ₹50 crore',
    target_date: null,
    amount_inr: 5000000000,
    status: 'announced',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-centre-applied-ai',
    ai_summary: 'Karnataka has committed ₹50 crore to establish a Centre for Applied AI. No procurement has been issued, no site selected, and no progress report published as of June 2026.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '2',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'education',
    text: 'Integrate AI tools into every government school classroom across Karnataka',
    target_date: null,
    amount_inr: null,
    status: 'announced',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-ai-schools',
    ai_summary: 'The state promised AI tools in every government school. No tender has been floated, no vendor selected, and no pilot results published.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '3',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'startup',
    text: 'Nurture 25,000 AI-ready startups in Karnataka by 2027',
    target_date: '2027-12-31',
    amount_inr: null,
    status: 'in_progress',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-25000-startups',
    ai_summary: 'Karnataka aims for 25,000 AI-ready startups by 2027. Current baseline and tracking methodology are undefined.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '4',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'infrastructure',
    text: 'Position Bengaluru as the deep tech capital of South Asia',
    target_date: null,
    amount_inr: null,
    status: 'announced',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-deep-tech-capital',
    ai_summary: 'The policy designates Bengaluru as a global deep tech hub. No international benchmarking or measurement framework has been published.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '5',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'governance',
    text: 'Establish an AI Governance Framework and Ethics Board for Karnataka',
    target_date: null,
    amount_inr: null,
    status: 'delayed',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-ai-ethics-board',
    ai_summary: 'An AI Ethics Board was proposed to oversee governance. It has not been constituted; no members or mandate published.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '6',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'governance',
    text: 'Deploy AI-powered citizen services across all government departments',
    target_date: null,
    amount_inr: null,
    status: 'announced',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-ai-citizen-services',
    ai_summary: 'AI-powered citizen services were promised across all departments. No deployment timeline or department-wise rollout plan is public.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
  {
    id: '7',
    state_id: 'ka-001',
    document_id: 'doc-001',
    category: 'agriculture',
    text: 'Create a Centre of Excellence for AI in Agriculture to support farmers',
    target_date: null,
    amount_inr: null,
    status: 'announced',
    last_verified_at: '2026-06-01T00:00:00Z',
    slug: 'ka-ai-agriculture-coe',
    ai_summary: 'A Centre of Excellence for AI in Agriculture was announced. No site, budget, or advisory board has been identified.',
    created_at: '2024-01-01T00:00:00Z',
    updated_at: '2026-06-01T00:00:00Z',
    evidence: [],
  },
]

export const mockRTIs: RTIFiling[] = [
  {
    id: 'rti-001',
    state_id: 'ka-001',
    filed_date: '2026-06-14',
    department: 'Department of Electronics, IT, BT and S&T',
    subject: 'Budget utilisation for ₹50 crore Centre for Applied AI',
    status: 'pending',
    response_date: null,
    response_summary: null,
    filing_url: null,
    response_url: null,
    created_at: '2026-06-14T00:00:00Z',
  },
  {
    id: 'rti-002',
    state_id: 'ka-001',
    filed_date: '2026-06-14',
    department: 'Department of Primary and Secondary Education',
    subject: 'Status of AI integration in government school classrooms',
    status: 'pending',
    response_date: null,
    response_summary: null,
    filing_url: null,
    response_url: null,
    created_at: '2026-06-14T00:00:00Z',
  },
]
